# Base image only for runtime
FROM oven/bun:1-alpine AS base
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Dependencies build stage
FROM oven/bun:1-alpine AS deps
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# Builder stage
FROM oven/bun:1-alpine AS builder
ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG NEXT_PUBLIC_AUTH_URL
ARG DATABASE_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG PGHOST
ARG PGUSER
ARG PGPASSWORD
ARG PGDATABASE
ARG PGPORT
ARG NEO4J_URI
ARG NEO4J_USERNAME
ARG NEO4J_PASSWORD
ARG NEO4J_DATABASE
ARG AURA_INSTANCEID
ARG AURA_INSTANCENAME
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG PHONE_NUMBER
ARG COUNTRY_CODE

ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL
ENV NEXT_PUBLIC_AUTH_URL=$NEXT_PUBLIC_AUTH_URL
ENV DATABASE_URL=$DATABASE_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV PGHOST=$PGHOST
ENV PGUSER=$PGUSER
ENV PGPASSWORD=$PGPASSWORD
ENV PGDATABASE=$PGDATABASE
ENV PGPORT=$PGPORT
ENV NEO4J_URI=$NEO4J_URI
ENV NEO4J_USERNAME=$NEO4J_USERNAME
ENV NEO4J_PASSWORD=$NEO4J_PASSWORD
ENV NEO4J_DATABASE=$NEO4J_DATABASE
ENV AURA_INSTANCEID=$AURA_INSTANCEID
ENV AURA_INSTANCENAME=$AURA_INSTANCENAME
ENV UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL
ENV UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN
ENV PHONE_NUMBER=$PHONE_NUMBER
ENV COUNTRY_CODE=$COUNTRY_CODE
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN bun run build

# Final runtime stage (minimal)
FROM oven/bun:1-alpine AS runner
WORKDIR /app

# Create non-root user
RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

# Copy only production deps
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

# Copy only necessary build outputs
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

# Permissions
RUN chown -R nextjs:nodejs /app
USER nextjs

EXPOSE 3000
CMD ["bun", "run", "start"]
